name: Auto-approve dependabot PRs

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

permissions:
  pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all PRs
        # Auto approve PRs that are 20 days old, for security
        run: |
          gh search prs org:openactive --state=open --author "app/dependabot" --json url,createdAt --label "dependencies" --state open --review required --limit 100 --jq '.[] | select((.createdAt | fromdateiso8601) < (now - (20*24*60*60))) | .url' | tee prs.txt
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

      - name: Approve PRs
        run: |
          while IFS= read -r pr
          do
            echo "Approving PR $pr ..."
            gh pr review --approve $pr
          done < prs.txt
        env:
          GH_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
